name: Build Documentation
on: [pull_request]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: mkdir build
      - name: Build Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: api-documentation
          path: build/doxygen/html/

  sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: mkdir build
      - run: sudo apt-get update && sudo apt-get install -y git
      - name: Build documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs/
          build-command: make html
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: user-documentation
          path: build/sphinx/html/
